commerce_sheets.settings:
  type: config_object
  label: 'Commerce Sheets settings'
  import:
    type: mapping
    label: 'Import settings'
    mapping:
      mode:
        # @I Check if there's an enumartion config property type
        type: integer
        label: 'Import mode'

commerce_sheets.commerce_sheets_import_type.*:
  type: commerce_config_entity_bundle
  label: 'Import type'
  mapping:
    description:
      type: text
      label: 'Description'
